---
title: "Hacking for Science 2024"
subtitle: "Background Survey"
author: "Matthias Bannert, RSEED"
format: 
    revealjs:
        logo: img/h4sci-logo.png
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
library(RPostgres)
library(DBI)
library(tidyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(quanteda)
library(quanteda.textplots)
library(quanteda.textstats)

preprocess <- function(df, pattern){
  pattern_id <- paste0("id|", pattern)
  subs <- df[ ,grepl(pattern_id, names(df))]
  names(subs) <- gsub(pattern,"",names(subs))
  dt <- as.data.table(subs)
  m <- melt(dt, id.vars = c("id"))
  m
}

con <- dbConnect(
  drv = Postgres(),
  dbname = "kofdb",
  port =  5432,
  user = Sys.getenv("PG_USER"),
  password = Sys.getenv("PG_PASSWORD"),
  host = Sys.getenv("PG_HOST")
  )

res <- dbGetQuery(con, "SELECT * FROM rseed.h4sci_intro")

dbDisconnect(con)

```



## Conceptual Foundations

```{r, echo=FALSE}
words_ice <- gsub(" vs. |,,|\\(|\\)", "", paste(res$icebreaker, collapse = ","))
words_ice <- gsub("\\/", " ", words_ice)
words_ice <- unlist(strsplit(words_ice, ","))

ice_tok <- tokens(words_ice)
ice_comp <- tokens_compound(ice_tok, pattern = phrase(words_ice))

ice_comp |> 
  dfm() |> 
  textstat_frequency() |> 
  ggplot(aes(x = reorder(feature, frequency), y = frequency)) +
  geom_point() +
  coord_flip() +
  labs(x = NULL, y = "Frequency") +
  theme_minimal()



```



## Reporting


```{r, echo=FALSE}
words_reporting <- gsub(" vs. |,,|\\(|\\)", "", paste(res$reporting, collapse = ","))
words_reporting <- gsub("\\/", " ", words_reporting)
words_reporting <- unlist(strsplit(words_reporting, ","))

reporting_tok <- tokens(words_reporting)
reporting_comp <- tokens_compound(reporting_tok, pattern = phrase(words_reporting))


reporting_comp |> 
  dfm() |> 
  textstat_frequency() |> 
  ggplot(aes(x = reorder(feature, frequency), y = frequency)) +
  geom_point() +
  coord_flip() +
  labs(x = NULL, y = "Frequency") +
  theme_minimal()


```


## Programming Languages

```{r, echo = FALSE}
lang <- preprocess(res, "l_")
gg_lang <- ggplot(data = lang)
gg_lang +
  geom_bar(aes(x = value, fill = variable)) +
  facet_wrap("variable", nrow = 2) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.spacing = unit(4, "lines")) +
  scale_x_discrete(name ="Language",
                   limits=factor(1:5)) +
  scale_fill_viridis_d() +
  coord_flip()



```


## Infrastructure



```{r, echo = FALSE}

infra <- preprocess(res, "i_")
gg_lang <- ggplot(data = infra)
gg_lang +
  geom_bar(aes(x = value, fill = variable)) +
  facet_wrap("variable", nrow = 2) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.spacing = unit(4, "lines")) +
  scale_x_discrete(name ="Technology",
                   limits=factor(1:5)) +
  scale_fill_viridis_d() +
  coord_flip()




```


## And the Winner is! 

```{r}
set.seed(123)
sample(substr(res$id,1,8),1)
```



