---
title: |
  Hacking for Social Sciences
subtitle: "Connect to Remote Repositories Like a Hacker"
author: "@whatsgoodio"
institute: "KOF, ETH Zurich"
date: "2020-10-02"
output:
  xaringan::moon_reader:
    css: ["robot-fonts","more.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      beforeInit: "https://platform.twitter.com/widgets.js"
---

class: center, middle

> 'With SSH keys, you can connect to remote git repositories without supplying your username or password at each visit'

-- docs.github.com



---


## What is an SSH Key Pair

- a key pair consists of a public and private key
- think: public key = flexible lock, private key = key 
- let server admins add your lock (public key) to all servers you want to be able to login to
- use the private key to log in to servers that got your lock mounted.
- if you loose the key, let the admin know to remove your lock -> keys is useless.
- optional passphrase can buy you time to inform the admin

for more context information read the [corresponding chapter in the online book](https://h4sci.github.io/h4sci-book/developer-practices-workflows.html#rsa-key-pair-authentication). 





---



class: center, middle

## 2 Options to Create a Key Pair: 
## A) Use R Studio Server B) Create Key Pair Locally







---

## R Studio Server: Login  (Option A)

- Go to [teaching.kof.ethz.ch](https://teaching.kof.ethz.ch) and log-in with the 
password and username provided to you at the start of the course. 

- Go to Tools -> Global Options -> Git/SVN and choose 'create RSA Key Pair'

- Leave the optional passphrase empty. Click 'Create'. The subsequent random art 
image just let's you know that you've been successful. Nerdy. Close the window.


---


## Create the Key Pair Locally (Option B)

Open a terminal / console (OSX / Linux) or git bash (Windows) and run: 

```bash
ssh-keygen -t rsa -b 4096 -C "your_email@somewhere.com"
```

just press enter to store the output in the default location (~/.ssh).
Leave the optional passphrase empty. 


---


## Entering your Key at GitHub: 1. Obtain the Key


From R Studio Server

- Go to Tools -> Global Options -> Git/SVN
- Click View Public Key
- Copy Key to Clipboard


From your local Machine

- Go to the hidden directory that stores the key: `cd ~/.ssh`
- open the file `id_rsa.pub` copy its content to your clipboard. NEVER use id_rsa (that's private!!).


---


## Entering your Key at GitHub: 2. Paste to Github


- Go to https://github.com/settings/keys and Log in to your profile. 

- Click 'New SSH Keys' and copy and paste the key

Good job, admin. You're good to go! 































